# Generated by Django 5.1.6 on 2025-02-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_appointment_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('age', models.CharField(default='unknown', max_length=2)),
                ('phone', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Orthopedics', 'Orthopedics'), ('General Medicine', 'General Medicine'), ('Ophthalmologist', 'Ophthalmologist'), ('Skin Care', 'Skin Care')], default='General Medicine', max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(default='No message')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
